name: Kryptokrona Main Pipeline

env:
  GITHUB_REGISTRY: "ghcr.io"
  GITHUB_OWNER: "kryptokrona"
  GITHUB_DOCKER_IMAGE: "kryptokrona"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build: ${{ matrix.config.name }} / ${{ matrix.config.platform }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
              name: "Ubuntu 20.04 GCC",
              artifact: "kryptokrona-ubuntu-20.zip",
              os: ubuntu-20.04,
              cc: "gcc",
              cxx: "g++",
              platform: x64,
            }
          - {
              name: "Ubuntu 22.04 GCC",
              artifact: "kryptokrona-ubuntu-22.zip",
              os: ubuntu-22.04,
              cc: "gcc",
              cxx: "g++",
              platform: x64,
            }
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        if: matrix.config.name == 'ubuntu-20.04' || matrix.config.name == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libboost-dev libboost-all-dev libssl-dev libffi-dev python3-dev gcc-11 g++-11 git cmake librocksdb-dev cron rpcbind libboost-system1.74.0 libboost-filesystem1.74.0 libboost-thread1.74.0 libboost-date-time1.74.0 libboost-chrono1.74.0 libboost-regex1.74.0 libboost-serialization1.74.0 libboost-program-options1.74.0 libicu70

      - name: mkdir build
        if: matrix.config.name == 'ubuntu-20.04' || matrix.config.name == 'ubuntu-22.04'
        run: mkdir build

      - name: Build Ubuntu Target
        if: matrix.config.name == 'ubuntu-20.04' || matrix.config.name == 'ubuntu-22.04'
        run: |
          cmake -DCMAKE_CXX_FLAGS="-g0 -Os -fPIC -std=gnu++17" -DBoost_ARCHITECTURE=-x64 .. # add flag -DBoost_DEBUG=ON to debug
          make -j$(nproc) --ignore-errors
        working-directory: build

      - name: Upload Ubuntu Artifact
        if: matrix.config.name == 'ubuntu-20.04' || matrix.config.name == 'ubuntu-22.04'
        uses: actions/upload-artifact@v3
        with:
          name: matrix.config.artifact
          path: |
            build/src/kryptokronad
            build/src/xkrwallet
            build/src/kryptokrona-service
            build/src/miner
            build/src/wallet-api

  test:
    name: Tests
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - name: Static Code Analysis
        run: echo "Running Static Code Analysis..."

      - name: Unit Test
        run: echo "Running Unit Tests..."

      - name: Code Coverage
        run: echo "Running Code Coverage..."

  doxygen:
    name: Doxygen
    runs-on: ubuntu-22.04
    needs: [test]
    steps:
      - uses: actions/checkout@v2

      - name: Doxygen
        run: echo "Running Doxygen..."

  docker:
    name: Build and Publish Docker Image
    runs-on: ubuntu-22.04
    needs: [doxygen]
    steps:
      - uses: actions/checkout@v2
      - uses: benjlevesque/short-sha@v1.2

      - name: Log into registry ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker
        run: |
          docker build -t $GITHUB_REGISTRY/$GITHUB_OWNER/$GITHUB_DOCKER_IMAGE:${{ env.SHA }} .

      - name: Publish Docker
        run: |
          docker push $GITHUB_REGISTRY/$GITHUB_OWNER/$GITHUB_DOCKER_IMAGE:${{ env.SHA }}
